Add partitioner for n-level graph partitioning
kahypar/mt-kahypar pull request #110
Opened 2022-04-01 16:46 UTC by N-Maas

Additional refactorings along the way:
- extracted some functionality from `dynamic_hypergraph` to `contraction_tree`
- made `copy()` `const` for all graph data structures

2022-04-05 08:43 UTC, kittobi1992 requested changes

2022-04-05 08:43 UTC, kittobi1992 commented on mt-kahypar/datastructures/dynamic_adjacency_array.cpp
> +parallel::scalable_vector<DynamicAdjacencyArray::RemovedEdgesOrWeight> DynamicAdjacencyArray::removeSinglePinAndParallelEdges() {
as we have discussed ...

2022-04-05 08:43 UTC, kittobi1992 commented on mt-kahypar/datastructures/dynamic_adjacency_array.cpp
> +parallel::scalable_vector<DynamicAdjacencyArray::RemovedEdgesOrWeight> DynamicAdjacencyArray::removeSinglePinAndParallelEdges() {
as we have discussed ...

2022-04-08 07:38 UTC, N-Maas commented on mt-kahypar/datastructures/dynamic_adjacency_array.cpp
> +      } else if (e.isValid()) {
as discussed

2022-04-08 07:38 UTC, N-Maas commented on mt-kahypar/datastructures/dynamic_adjacency_array.cpp
> +      } else if (e.isValid()) {
as discussed

2022-04-08 10:05 UTC, merged